const Animals = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Ant",
    "Armadillo",
    "Axolotl",
    "Aye-Aye",
    "Badger",
    "Banded Palm Civet",
    "Bandicoot",
    "Barnacle",
    "Barracuda",
    "Basilisk Lizard",
    "Basking Shark",
    "Bear",
    "Beaver",
    "Bedbug",
    "Bee",
    "Beetle",
    "Binturong",
    "Bird",
    "Birds Of Paradise",
    "Bison",
    "Blobfish",
    "Booby",
    "Bongo",
    "Bonito Fish",
    "Bonobo",
    "Booby",
    "Bovid",
    "Buffalo",
    "Bug",
    "Butterfly",
    "Buzzard",
    "Carp",
    "Cat",
    "Cheetah",
    "Chameleon",
    "Cockroach",
    "Cod",
    "Coelacanth",
    "Cheetah",
    "Chameleon",
    "Dolphin",
    "Duck",
    "Elephant",
    "Eagle",
    "Fox",
    "Frog",
    "Giraffe",
    "Gorilla",
    "Hawk",
    "Hippopotamus",
    "Iguana",
    "Ibis",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Lemur",
    "Lion",
    "Meerkat",
    "Monkey",
    "Narwhal",
    "Newt",
    "Orangutan",
    "Ostrich",
    "Penguin",
    "Peacock",
    "Quetzal",
    "Quokka",
    "Raccoon",
    "Rhinoceros",
    "Shark",
    "Sloth",
    "Tiger",
    "Toucan",
    "Uakari",
    "Umbrellabird",
    "Viper",
    "Vulture",
    "Wallaby",
    "Wombat",
    "X-ray Tetra",
    "Xenops",
    "Yabby",
    "Yak",
    "Zebra",
    "Zorse",
    "Albatross",
    "Aye-Aye",
    "Badger",
    "Banded Palm Civet",
    "Bandicoot",
    "Barnacle",
    "Barracuda",
    "Basilisk Lizard",
    "Basking Shark",
    "Bison",
    "Blobfish",
    "Booby",
    "Bongo",
    "Bonito Fish",
    "Bonobo",
    "Bovid",
    "Buffalo",
    "Bug",
    "Butterfly",
    "Buzzard",
    "Carp",
    "Cat",
    "Cockroach",
    "Cod",
    "Coelacanth",
    "Cuttlefish",
    "Dung Beetle",
    "Earwig",
    "Echidna",
    "Falcon",
    "Fiddler Crab",
    "Firefly",
    "Flatworm",
    "Flying Squirrel",
    "Gazelle",
    "Gecko",
    "Gibbon",
    "Glass Lizard",
    "Glow Worm",
    "Gnu",
    "Goblin Shark",
    "Goldfish",
    "Goose",
    "Gopher",
    "Gudgeon",
    "Guinea Pig",
    "Guppy",
    "Hamster",
    "Harpy Eagle",
    "Hercules Beetle",
    "Hermit Crab",
    "Herring",
    "Hornet",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Impala",
    "Indigo Bunting",
    "Insect",
    "Jackal",
    "Jerboa",
    "Junglefowl",
    "Kinkajou",
    "Kiwi",
    "Kookaburra",
    "Kowari",
    "Lamprey",
    "Leaf-Tailed Gecko",
    "Leech",
    "Lemming",
    "Limpet",
    "Lobster",
    "Locust",
    "Mantis Shrimp",
    "Mantis",
    "Marmoset",
    "Marsupial",
    "Mastodon",
    "Mayfly",
    "Midge",
    "Millipede",
    "Mole",
    "Mollusk",
    "Mongoose",
    "Monitor Lizard",
    "Moth",
    "Mouse",
    "Mule",
    "Nightingale",
    "Nudibranch",
    "Numbat",
    "Nurse Shark",
    "Okapi",
    "Olm",
    "Opossum",
    "Owl",
    "Panda",
    "Parrot",
    "Peafowl",
    "Pelican",
    "Penguin",
    "Pheasant",
    "Pig",
    "Pika",
    "Piranha",
    "Planarian",
    "Platypus",
    "Poodle",
    "Porcupine",
    "Quail",
    "Quokka",
    "Quoll",
    "Rabbit",
    "Rat",
    "Reindeer",
    "Reticulated Python",
    "Rhinoceros",
    "Sable",
    "Salamander",
    "Sardine",
    "Scorpion",
    "Sea Dragon",
    "Sea Slug",
    "Sea Squirt",
    "Sea Urchin",
    "Seahorse",
    "Seal",
    "Shrimp",
    "Skunk",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Snipe",
    "Snow Leopard",
    "Sparrow",
    "Spider",
    "Sponge",
    "Squid",
    "Squirrel",
    "Star-Nosed Mole",
    "Starfish",
    "Stonefish",
    "Sturgeon",
    "Sun Bear",
    "Swordfish",
    "Tapeworm",
    "Tarantula",
    "Tarsier",
    "Termite",
    "Thorny Devil",
    "Tiger Beetle",
    "Tiger Shark",
    "Tiger Snake",
    "Tiglon",
    "Tortoise",
    "Toucan",
    "Tree Frog",
    "Tsetse Fly",
    "Uakari",
    "Uguisu",
    "Umbrellabird",
    "Unicorn",
    "Urial",
    "Vampire Bat",
    "Vampire Squid",
    "Vicuna",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Warthog",
    "Wasp",
    "Water Buffalo",
    "Weasel",
    "Weevil",
    "Whale",
    "Whippet",
    "Whitefish",
    "Wild Boar",
    "Wildebeest",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodpecker",
    "Wrasse",
    "Wrench",
    "Wryneck",
    "X-Ray Tetra",
    "X-Ray Fish",
    "Xantus's Hummingbird",
    "Xeme",
    "Xenarthra",
    "Xenomorph",
    "Xenophyophore",
    "Xenops",
    "Xenopus",
    "Xerus",
    "Xiaosaurus",
    "Xoloitzcuintli",
    "X-Ray Crab",
    "X-Ray Shrimp",
    "Yaffle",
    "Yak",
    "Yapok",
    "Yardang",
    "Yellow-Eyed Penguin",
    "Yellowjacket",
    "Yelling Cat",
    "Yerevan",
    "Yeti Crab",
    "Yew",
    "Ylva",
    "Yo-Yo",
    "Yodeler",
    "Yoshi",
    "Yowie",
    "Yoyo",
    "Yurt",
    "Zander",
    "Zebra",
    "Zebu",
    "Zedonk",
    "Zebra Shark",
    "Zebra Turkeyfish",
    "Zorse"
]

const People = [
    { firstName: "Christian", lastName: "Davis" },
    { firstName: "Ada", lastName: "Lovelace" },
    { firstName: "Abraham", lastName: "Lincoln" },
    { firstName: "Albert", lastName: "Einstein" },
    { firstName: "Alice", lastName: "Johnson" },
    { firstName: "Barack", lastName: "Obama" },
    { firstName: "Bob", lastName: "Smith" },
    { firstName: "Cleopatra", lastName: "Jones" },
    { firstName: "Charles", lastName: "Darwin" },
    { firstName: "Charlie", lastName: "Davis" },
    { firstName: "Coco", lastName: "Chanel" },
    { firstName: "David", lastName: "Bowie" },
    { firstName: "Emily", lastName: "Brown" },
    { firstName: "Emmeline", lastName: "Pankhurst" },
    { firstName: "Frank", lastName: "Johnson" },
    { firstName: "Frida", lastName: "Kahlo" },
    { firstName: "Galileo", lastName: "Galilei" },
    { firstName: "Grace", lastName: "Taylor" },
    { firstName: "Grace", lastName: "Hopper" },
    { firstName: "Henry", lastName: "Clark" },
    { firstName: "Helen", lastName: "Keller" },
    { firstName: "Ivy", lastName: "Robinson" },
    { firstName: "Isaac", lastName: "Newton" },
    { firstName: "Jack", lastName: "Anderson" },
    { firstName: "Jane", lastName: "Austen" },
    { firstName: "John", lastName: "Doe" },
    { firstName: "John", lastName: "Kennedy" },
    { firstName: "Katherine", lastName: "Miller" },
    { firstName: "Kylie", lastName: "Johnson" },
    { firstName: "Leonardo", lastName: "da Vinci" },
    { firstName: "Louis", lastName: "Turner" },
    { firstName: "Mia", lastName: "Hill" },
    { firstName: "Marie", lastName: "Curie" },
    { firstName: "Martin", lastName: "King Jr." },
    { firstName: "Nelson", lastName: "Mandela" },
    { firstName: "Noah", lastName: "Parker" },
    { firstName: "Olivia", lastName: "Rossi" },
    { firstName: "Pablo", lastName: "Picasso" },
    { firstName: "Paul", lastName: "White" },
    { firstName: "Quinn", lastName: "Miller" },
    { firstName: "Queen", lastName: "Elizabeth II" },
    { firstName: "Robert", lastName: "Davis" },
    { firstName: "Rosa", lastName: "Parks" },
    { firstName: "Sophia", lastName: "Walker" },
    { firstName: "Steve", lastName: "Jobs" },
    { firstName: "Thomas", lastName: "Edison" },
    { firstName: "Tom", lastName: "Thompson" },
    { firstName: "Ursula", lastName: "Smith" },
    { firstName: "Victor", lastName: "Garcia" },
    { firstName: "Vincent", lastName: "van Gogh" },
    { firstName: "Wendy", lastName: "Jones" },
    { firstName: "William", lastName: "Shakespeare" },
    { firstName: "Winston", lastName: "Churchill" },
    { firstName: "Xander", lastName: "Johnson" },
    { firstName: "Yvonne", lastName: "Miller" },
    { firstName: "Zachary", lastName: "Wilson" },
    { firstName: "Zhang", lastName: "Heng" }
]

const Buildings = [
    "Angkor Wat",
    "Big Ben",
    "Brandenburg Gate",
    "Burj Khalifa",
    "Christ the Redeemer",
    "Colosseum",
    "Eiffel Tower",
    "Forbidden City",
    "Great Wall of China",
    "Hagia Sophia",
    "Louvre Museum",
    "Machu Picchu",
    "Neuschwanstein Castle",
    "Petra",
    "Pyramids of Giza",
    "Sagrada Familia",
    "Sydney Opera House",
    "Taj Mahal",
    "The White House",
    "Tokyo Tower",
    "Blue Mosque",
    "Buckingham Palace",
    "Casa Milà",
    "Casa Batlló",
    "Château de Versailles",
    "Cologne Cathedral",
    "Dresden Frauenkirche",
    "Gherkin",
    "Golden Gate Bridge",
    "Great Mosque of Djenne",
    "Himeji Castle",
    "Statue of Liberty",
    "Stonehenge",
    "Taipei 101",
    "The Shard",
    "Tower Bridge",
    "Uffizi Gallery",
    "Willis Tower",
    "Windsor Castle",
    "Yellow Crane Tower"
]

const Climates = [
    "Alpine",
    "Arid",
    "Boreal Forest",
    "Chaparral",
    "Cold Highland",
    "Cold Monsoon",
    "Cold Oceanic",
    "Cold Wetland",
    "Cold Oceanic",
    "Cold Ice Cap",
    "Dry Steppe",
    "Dry Swamp",
    "Dry Tundra",
    "Dry Wetland",
    "Equatorial",
    "Equatorial Guinea Climate",
    "Equatorial Monsoon",
    "Hot Rainforest",
    "Hot Savannah",
    "Hot Steppe",
    "Hot Swamp",
    "Hot Tundra",
    "Hot Wetland",
    "Hot Ice Cap",
    "Humid Continental",
    "Humid Subtropical",
    "Ice Cap",
    "Mangrove",
    "Mediterranean",
    "Mediterranean Forest",
    "Monsoon",
    "Mountain",
    "Polar",
    "Polar Alpine",
    "Polar Desert",
    "Polar Ice Cap",
    "Polar Maritime",
    "Polar Tundra",
    "Polar Wetland",
    "Polar Oceanic",
    "Prairie",
    "Subtropical Steppe",
    "Subtropical Wetland",
    "Swamp",
    "Taiga",
    "Temperate Oceanic",
    "Temperate Rainforest",
    "Thundra",
    "Tropical Arid",
    "Tundra",
    "Warm Arid",
    "Warm Oceanic",
    "Warm Steppe",
    "Wetland",
    "Xanthus's Hummingbird",
    "Xeme",
    "Xenomorph",
    "Xenophyophore",
    "Xenops",
    "Xenopus",
    "Xerus",
    "Xiaosaurus",
    "Xoloitzcuintli",
    "X-Ray Crab",
    "X-Ray Fish",
    "X-Ray Shrimp",
    "Yellow-Eyed Penguin",
    "Yellowjacket",
    "Yelling Cat",
    "Yerevan",
    "Yeti Crab",
    "Yew",
    "Ylva",
    "Yo-Yo",
    "Yodeler",
    "Yoshi",
    "Yowie",
    "Yoyo",
    "Yurt",
    "Zander",
    "Zebra",
    "Zebra Shark",
    "Zebra Turkeyfish",
    "Zedonk"
]

const Countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Islamic Republic of Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Democratic People's Republic of Korea",
    "Republic of Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Romania",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland Islands"
]

const States = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
]

const Capitals = [
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "St. Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Cheyenne",
    "Tokyo",       
    "Paris",       
    "Berlin",      
    "Cairo",       
    "Moscow",      
    "Seoul",       
    "Oslo",        
    "Wellington",  
    "Beijing",     
    "Rome"
]

const Foods = [
    "Almond",
    "Apple",
    "Apple Pie",
    "Asparagus",
    "Banana",
    "Barley",
    "Beef",
    "Broccoli",
    "Brownie",
    "Butter",
    "Candy",
    "Carrot",
    "Cheese",
    "Cherry",
    "Chicken",
    "Couscous",
    "Daikon",
    "Date",
    "Doughnut",
    "Duck",
    "Durian",
    "Eclair",
    "Egg",
    "Eggplant",
    "Elderberry",
    "Einkorn",
    "Evaporated Milk",
    "Fennel",
    "Feta",
    "Fig",
    "Fish",
    "Fudge",
    "Gelato",
    "Garlic",
    "Grapes",
    "Grits",
    "Grouper",
    "Habanero",
    "Halibut",
    "Havarti",
    "Hempseed",
    "Honeydew",
    "Hot Fudge Sundae",
    "Ice Cream",
    "Ice Cream Sandwich",
    "Iceberg Lettuce",
    "Israeli Couscous",
    "Jalapeño Jack",
    "Jelly Beans",
    "Jellyfish",
    "Kiwi",
    "Kale",
    "Kamut",
    "Kettle Corn",
    "Lamb",
    "Lemon",
    "Lemon Bars",
    "Lettuce",
    "Macarons",
    "Mango",
    "Milk",
    "Mousse",
    "Mushroom",
    "Mussels",
    "Napa Cabbage",
    "Natto",
    "Nondairy Yogurt",
    "Nougat",
    "Oatmeal Raisin Cookies",
    "Olive Oil",
    "Orange",
    "Ostrich",
    "Papaya",
    "Parmesan",
    "Peach",
    "Pear",
    "Pecan",
    "Pepper",
    "Pesto",
    "Pineapple",
    "Pork",
    "Potato",
    "Pudding",
    "Pumpkin",
    "Quark",
    "Quiche",
    "Quinoa",
    "Raspberry",
    "Rice",
    "Sausage",
    "Shrimp",
    "Sorghum",
    "Soy Milk",
    "Spinach",
    "Strawberry",
    "Sushi",
    "Taco",
    "Tapioca",
    "Tea",
    "Teff",
    "Toffee",
    "Udon",
    "Vanilla",
    "Walnut",
    "Watermelon",
    "Wonton",
    "Yogurt"
]

const PlayingArrays = {
    Animals, 
    People,
    Buildings,
    Climates,
    Countries,
    States,
    Capitals,
    Foods
}